"""Ramo Brasil + conectores internos do OSINT4ALL."""

from __future__ import annotations

from typing import Any


def _url(
    name: str,
    url: str,
    *,
    description: str,
    input_type: str,
    output: str,
    internal: bool = False,
    edit_url: bool = False,
    registration: bool = False,
) -> dict[str, Any]:
    return {
        "name": name,
        "type": "url",
        "url": url,
        "description": description,
        "status": "live",
        "pricing": "free",
        "bestFor": description,
        "input": input_type,
        "output": output,
        "opsec": "passive",
        "localInstall": False,
        "googleDork": False,
        "registration": registration,
        "editUrl": edit_url,
        "api": False,
        "internal": internal,
        "source": "osint4all",
    }


def brazil_branch() -> dict[str, Any]:
    return {
        "name": "Brasil · oficiais",
        "type": "folder",
        "source": "osint4all",
        "children": [
            {
                "name": "Empresas e sócios",
                "type": "folder",
                "children": [
                    _url(
                        "Minha Receita (CNPJ)",
                        "https://minhareceita.org/{seed}",
                        description="Consulta pública de CNPJ com QSA (quadro de sócios).",
                        input_type="CNPJ",
                        output="Razão social, CNAE, sócios e situação cadastral",
                        edit_url=True,
                    ),
                    _url(
                        "BrasilAPI CNPJ",
                        "https://brasilapi.com.br/api/cnpj/v1/{seed}",
                        description="API pública de CNPJ.",
                        input_type="CNPJ",
                        output="JSON com dados cadastrais e QSA",
                        edit_url=True,
                    ),
                    _url(
                        "Receita Federal · CNPJ",
                        "https://solucoes.receita.fazenda.gov.br/servicos/cnpjreva/cnpjreva_solicitacao.asp",
                        description="Comprovante de inscrição e situação cadastral.",
                        input_type="CNPJ",
                        output="Comprovante oficial",
                    ),
                    _url(
                        "OSINT4ALL · conector CNPJ",
                        "/app/ferramentas?tool=cnpj",
                        description="Ficha e QSA no painel (Minha Receita / BrasilAPI). Dá para atribuir ao caso corrente.",
                        input_type="CNPJ",
                        output="Nós ORG/PERSON e arestas SOCIO/ADMIN",
                        internal=True,
                    ),
                    _url(
                        "OSINT4ALL · rede societária",
                        "/app/ferramentas?tool=name",
                        description="Busca empresas pelo nome do sócio no painel. Vistas Rede, Árvore, Split e Mapa no grafo.",
                        input_type="Nome do sócio",
                        output="Empresas, co-sócios, CNAE, situação e município",
                        internal=True,
                    ),
                    _url(
                        "Brasil.IO · sócios",
                        "https://brasil.io/dataset/socios-brasil/socios/",
                        description="Dataset público de QSA extraído dos dados abertos da Receita Federal.",
                        input_type="Nome do sócio",
                        output="CNPJ e qualificação",
                    ),
                    _url(
                        "Receita · dados abertos CNPJ",
                        "https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica-cnpj",
                        description="Arquivos oficiais mensais de empresas, sócios e CNAE.",
                        input_type="—",
                        output="CSV da Receita Federal",
                    ),
                    _url(
                        "CAGED / Novo Caged",
                        "https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/estatisticas-trabalho/novo-caged",
                        description="Estatística oficial de emprego (não é salário individual).",
                        input_type="CNAE / município",
                        output="Movimentação formal",
                    ),
                    _url(
                        "Simulador MEI",
                        "https://www.gov.br/empresas-e-negocios/pt-br/empreendedor",
                        description="Portal oficial do MEI (DAS e enquadramento).",
                        input_type="Atividade",
                        output="Guia oficial",
                    ),
                ],
            },
            {
                "name": "Processos e diários",
                "type": "folder",
                "children": [
                    _url(
                        "DataJud (CNJ)",
                        "https://www.cnj.jus.br/sistemas/datajud/",
                        description="API pública de capa e movimentos processuais.",
                        input_type="CNJ",
                        output="Capa, classe, movimentos",
                    ),
                    _url(
                        "DJEN / Comunica",
                        "https://comunica.pje.jus.br/",
                        description="Diário de Justiça Eletrônico Nacional.",
                        input_type="Nome / CNJ / OAB",
                        output="Publicações e intimações",
                    ),
                    _url(
                        "OSINT4ALL · conectores judiciais",
                        "/app/ferramentas?tool=cnj",
                        description="Consulta o número CNJ no painel. DataJud e DJEN expandem no grafo ao atribuir ao caso.",
                        input_type="CNJ / nome / empresa",
                        output="Nós CASE e PUBLICATION",
                        internal=True,
                    ),
                ],
            },
            {
                "name": "Eleições e transparência",
                "type": "folder",
                "children": [
                    _url(
                        "TSE DivulgaCandContas",
                        "https://divulgacandcontas.tse.jus.br/",
                        description="Candidaturas, partidos e prestações de contas.",
                        input_type="Nome",
                        output="Cargo, partido, UF, ano",
                    ),
                    _url(
                        "PNCP · contratações",
                        "https://pncp.gov.br/app/editais?q={seed}",
                        description="Portal Nacional de Contratações Públicas. Sem chave.",
                        input_type="CNPJ / nome",
                        output="Editais e contratos",
                        edit_url=True,
                    ),
                    _url(
                        "Câmara · dados abertos",
                        "https://dadosabertos.camara.leg.br/swagger/api.html",
                        description="API pública de deputados, votações e despesas.",
                        input_type="Nome",
                        output="Mandato e partido",
                    ),
                    _url(
                        "OpenSanctions",
                        "https://www.opensanctions.org/search/?q={seed}",
                        description="PEP e sanções internacionais (busca pública).",
                        input_type="Nome / CNPJ",
                        output="Listas oficiais estrangeiras",
                        edit_url=True,
                    ),
                    _url(
                        "GLEIF · LEI",
                        "https://search.gleif.org/#/search/{seed}",
                        description="Identificador legal global de pessoa jurídica.",
                        input_type="Razão / CNPJ",
                        output="LEI e jurisdição",
                        edit_url=True,
                    ),
                    _url(
                        "Portal da Transparência",
                        "https://portaldatransparencia.gov.br/",
                        description="CEIS, CNEP, contratos e servidores.",
                        input_type="CPF / CNPJ",
                        output="Sanções e despesas públicas",
                        registration=True,
                    ),
                    _url(
                        "Portal da Transparência API",
                        "https://api.portaldatransparencia.gov.br/",
                        description="API oficial (exige chave gratuita).",
                        input_type="CPF / CNPJ",
                        output="JSON CEIS/CNEP",
                        registration=True,
                    ),
                    _url(
                        "TSE FiliaWeb",
                        "https://filiaweb.tse.jus.br/filiaweb/",
                        description="Consulta pública de filiação partidária.",
                        input_type="Nome",
                        output="Partido e situação de filiação",
                    ),
                    _url(
                        "TSE Dados Abertos",
                        "https://dadosabertos.tse.jus.br/",
                        description="Repositório oficial de dados eleitorais.",
                        input_type="Nome / partido",
                        output="Candidaturas, contas, eleitorado",
                    ),
                    _url(
                        "Câmara · votações",
                        "https://www.camara.leg.br/busca-portal/proposicoes/votacoes",
                        description="Votações da Câmara dos Deputados.",
                        input_type="Nome / proposição",
                        output="Votos públicos",
                    ),
                ],
            },
            {
                "name": "Tribunais e consultas (Brazuca)",
                "type": "folder",
                "children": [
                    _url(
                        "Consulta processual CNJ",
                        "https://www.cnj.jus.br/pjecnj/ConsultaPublica/listView.seam",
                        description="Consulta pública unificada (PJe CNJ).",
                        input_type="CNJ / nome",
                        output="Capa pública do processo",
                    ),
                    _url(
                        "BNMP · mandados de prisão",
                        "https://portalbnmp.cnj.jus.br/#/pesquisa-peca",
                        description="Banco Nacional de Mandados de Prisão (consulta pública).",
                        input_type="Nome",
                        output="Peças públicas de mandado",
                    ),
                    _url(
                        "Jurisprudência STF",
                        "https://jurisprudencia.stf.jus.br/",
                        description="Acórdãos e decisões do STF.",
                        input_type="Nome / tema",
                        output="Julgados",
                    ),
                    _url(
                        "PJe TST",
                        "https://pje.tst.jus.br/consultaprocessual/",
                        description="Consulta pública da Justiça do Trabalho.",
                        input_type="CNJ / nome",
                        output="Processo trabalhista",
                    ),
                    _url(
                        "JusBrasil",
                        "https://www.jusbrasil.com.br/",
                        description="Índice público de peças e notícias jurídicas.",
                        input_type="Nome / CNJ",
                        output="Menções processuais",
                    ),
                    _url(
                        "Escavador",
                        "https://www.escavador.com/",
                        description="Busca pública de pessoas, instituições e processos.",
                        input_type="Nome",
                        output="Menções em fontes públicas",
                    ),
                ],
            },
            {
                "name": "Veículos",
                "type": "folder",
                "children": [
                    _url(
                        "OSINT4ALL · placa",
                        "/app/ferramentas?tool=plate",
                        description="Consulta a placa no painel. Série histórica e vínculo com o dono se você informar o nome. Sem DETRAN de dono.",
                        input_type="Placa",
                        output="Nó VEHICLE + aresta PROPRIETARIO",
                        internal=True,
                    ),
                    _url(
                        "SENATRAN · consultas",
                        "https://www.gov.br/transportes/pt-br/assuntos/transito/conteudo-Senatran/consultas",
                        description="Portais oficiais de trânsito. Dono e restrições exigem Renavam/gov.br no site do governo.",
                        input_type="Placa + Renavam",
                        output="Consulta oficial no portal (não é API)",
                    ),
                    _url(
                        "SENATRAN · recalls",
                        "https://www.gov.br/transportes/pt-br/assuntos/transito/conteudo-Senatran/recalls",
                        description="Campanhas de recall por fabricante/modelo.",
                        input_type="Marca / modelo",
                        output="Recall oficial",
                    ),
                    _url(
                        "DETRAN-SP",
                        "https://www.detran.sp.gov.br/",
                        description="Consulta estadual (placa + Renavam). Não devolve o proprietário por API pública.",
                        input_type="Placa + Renavam",
                        output="Débitos e situação no portal",
                    ),
                ],
            },
            {
                "name": "Cadastros profissionais e empresa",
                "type": "folder",
                "children": [
                    _url(
                        "CPF · situação cadastral",
                        "https://servicos.receita.fazenda.gov.br/Servicos/CPF/ConsultaSituacao/ConsultaPublica.asp",
                        description="Consulta pública da situação do CPF (Receita).",
                        input_type="CPF",
                        output="Situação cadastral",
                    ),
                    _url(
                        "CNA · OAB",
                        "https://cna.oab.org.br/",
                        description="Cadastro Nacional dos Advogados.",
                        input_type="Nome / OAB",
                        output="Inscrição e seccional",
                    ),
                    _url(
                        "CFM · médicos",
                        "https://portal.cfm.org.br/busca-medicos/",
                        description="Busca pública no Conselho Federal de Medicina.",
                        input_type="Nome / CRM",
                        output="Registro profissional",
                    ),
                    _url(
                        "SINTEGRA",
                        "http://www.sintegra.gov.br/",
                        description="Inscrição estadual (consulta pública).",
                        input_type="CNPJ / IE",
                        output="Inscrição estadual",
                    ),
                    _url(
                        "CEIS",
                        "https://portaldatransparencia.gov.br/sancoes/consulta?cadastro=ceis",
                        description="Empresas inidôneas e suspensas.",
                        input_type="CNPJ / nome",
                        output="Sanção pública",
                    ),
                    _url(
                        "Jucesp",
                        "https://www.jucesponline.sp.gov.br/",
                        description="Junta Comercial de São Paulo (consulta pública).",
                        input_type="Nome / NIRE",
                        output="Ficha cadastral estadual",
                    ),
                ],
            },
            {
                "name": "Fonte do catálogo",
                "type": "folder",
                "children": [
                    _url(
                        "OSINT Brazuca",
                        "https://github.com/osintbrazuca/osint-brazuca",
                        description="Índice comunitário de portais públicos no contexto Brasil. Só fontes oficiais/públicas entram no mapa.",
                        input_type="—",
                        output="Lista de portais",
                    ),
                ],
            },
        ],
    }
